---
deployment:
  tasks:
    - export DEPLOYPATH=/home/roundnetenc/apps/website
    - export STORAGEPATH=/home/roundnetensc/apps/website_storage
    - /bin/rm -rf $DEPLOYPATH
    - /bin/cp -r ./*$DEPLOYPATH
    - /bin/cd $DEPLOYPATH
    - alias npm=/opt/cpanel/ea-nodejs10/bin/npm
    - alias node=/opt/cpanel/ea-nodejs10/bin/node
    - alias pip=/usr/bin/pip3
    - alias python=/usr/bin/python
    - npm install
    - npm run dev
    - pip install -r ./requirements.txt
    - python ./manage.py migrate
    - python ./manage.py collectstatic
    - /bin/ln -s $STORAGEPATH/media media