# Generated by Django 3.2.9 on 2021-11-05 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysignup',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='activities.activity'),
        ),
    ]
