# Generated by Django 3.2.9 on 2022-01-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='id',
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
