# Generated by Django 3.2.9 on 2022-01-05 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220105_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='page_id',
            new_name='page',
        ),
    ]
